[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 110
color = true
target-version = [
    "py39",
    "py310",
    "py311",
    "py312",
]
